### ISSUE TITLE
team meeting (2022-12-15)

### ISSUE THREAD

**Issue by dgkf** [pharmaR/regulatory-r-repo-wg#24]
Today we primarily ran through our collected issues so far. 

Overall, our meeting today was devoted to identifying areas of uncertainty as we get our project off the ground. Action items are focused on nailing down our vision, stakeholders, affiliates and immediate next steps.

- [x] Map out a more comprehensive, cohesive vision (https://github.com/pharmaR/regulatory-r-repo-wg/issues/21)
- [x] Clarify affiliates and their involvement (https://github.com/pharmaR/regulatory-r-repo-wg/issues/22)
- [ ] Reach out to R Validation Hub Exec to present at first meeting in new year (https://github.com/pharmaR/regulatory-r-repo-wg/issues/23)
