### ISSUE TITLE
Validation pipeline MVP:  job to process a package's dependencies 

### ISSUE THREAD

**Issue by yannfeat** [pharmaR/regulatory-r-repo-wg#63]
#### Description
Create the first job of the Validation pipeline MVP along with its accompanying script. This job will run a script that processes the target package's dependencies and then will pass the formatted list to the next jobs of the MVP.

#### Tasks
Include specific tasks in the order they need to be done in. Include links to specific lines of code where the task should happen at.
- [ ] Populate the r-val-pipeline branch with the files of a sample target package, including well-formatted DESCRIPTION and NAMESPACE files
- [ ] Create a script that processes the DESCRIPTION and NAMESPACE files, to return a list of the package's dependencies version
- [ ] Optionally, look into ways to specify and/or dynamically get the sources of the dependencies
- [ ] Provide the YAML template of a job that runs this script and passes the returned list of dependencies (with version and optionally the source) to other jobs
