### ISSUE TITLE
Validation pipeline MVP: job to format the results of multiple validation jobs

### ISSUE THREAD

**Issue by yannfeat** [pharmaR/regulatory-r-repo-wg#64]
#### Description
The last job of the the validation pipeline MVP's workflow, that will pull the results of all the [validatoR](https://github.com/insightsengineering/thevalidatoR) jobs run on the target package and its dependencies (designed in https://github.com/pharmaR/regulatory-r-repo-wg/issues/65), and then produce an overall validation report.

#### Tasks
- [x]  Write a JSON definition file
- [x] Write a script that returns JSON files containing information on the validation status of each package (target and dependencies)
- [x] Integrate the script in the pipeline

**Comment by Stefan-Doering-BI** [comment]
Created a PR (https://github.com/pharmaR/thevalidatoR/pull/5), which adds the JSON Definition file.

**Comment by yannfeat** [comment]
See https://github.com/pharmaR/thevalidatoR/pull/9
